sigoden/argc

README.md, src/cli.rs, src/parser.rs, tests/fail_test.rs, tests/snapshots/integration__spec_test__spec_cmd_alias.snap, tests/snapshots/integration__spec_test__spec_help.snap, tests/spec.sh, tests/spec_test.rs
=> feat: support subcommand aliases

Cargo.lock, Cargo.toml, src/cli.rs, tests/escape_test.rs, tests/snapshots/integration__spec_test__spec_cmd_option_names_exec.snap, tests/snapshots/integration__spec_test__spec_cmd_option_names_exec_eval.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_exec.snap, tests/snapshots/integration__spec_test__spec_cmd_preferred_exec.snap, tests/tests.rs
=> fix: shell escaple

README.md, src/cli.rs, src/parser.rs, tests/snapshots/integration__spec_test__spec_cmd_option_names_exec.snap, tests/snapshots/integration__spec_test__spec_cmd_option_names_exec_eval.snap, tests/snapshots/integration__spec_test__spec_cmd_option_names_help.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_and_default.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_and_default_exec.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_and_required.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_and_required_exec_fail.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_exec.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_choices_exec_fail.snap, tests/snapshots/integration__spec_test__spec_help.snap, tests/spec.sh, tests/spec_test.rs
=> feat: parameter with choices and required

README.md, src/parser.rs, tests/snapshots/integration__spec_test__spec_cmd_positional_with_default.snap, tests/snapshots/integration__spec_test__spec_cmd_positional_with_default_exec.snap, tests/snapshots/integration__spec_test__spec_help.snap, tests/spec.sh, tests/spec_test.rs
=> feat: positional parameter with default

src/main.rs
Your argcfile can be named any of the following:
- argcfile
- argcfile.sh
- Argcfile
- Argcfile.sh
=> feat: argcfile can be named with/without .sh suffix or captial

src/main.rs
first iter candicates , second go to parent directory
=> fix: get script path

README.md, argcfile, docs/command-runner.md, examples/demo.sh, examples/options.sh, examples/subcmds.sh, src/main.rs, tests/fixtures.rs, tests/spec.sh
```
eval $(argc --argc-eval "$0" "$@")
```
=> chore: update bash eval expression

README.md, src/main.rs, tests/create.rs, tests/fixtures.rs, tests/tests.rs
=> feat: add command to generate boilerplate argcfile

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs, tests/macros.rs
=> feat: support color

README.md, completions/argc.fish
=> feat: add fish completion

README.md, src/param.rs, src/parser.rs, tests/snapshots/integration__spec_test__spec_cmd_flag_formats_count.snap, tests/snapshots/integration__spec_test__spec_cmd_flag_formats_help.snap, tests/spec.sh, tests/spec_test.rs
=> feat: flag param support multiple

src/argc_value.rs, src/cli.rs, src/utils/argmap.rs, src/utils/mod.rs, tests/snapshots/integration__spec_test__spec_fn_args.snap, tests/spec.sh, tests/spec_test.rs
```
_choice_foo() {
echo "$argc_workdir"
echo $@
}
```
```
$ prog _choice_fn "--workdir /tmp a b c"
/tmp
a b c
```
It can generate completion based on current readline text.
=> feat: compgen param fn supports cli args

src/cli.rs, src/completion.rs, tests/compgen.rs, tests/snapshots/integration__compgen__dynamic_compgen.snap, tests/snapshots/integration__spec_test__spec_fn_args.snap
We can add `_compgen` fn to argc script to inject addtional completion candicates
```
_compgen() {
:;
}
```
=> feat: support dynamic compgen fn

src/cli.rs, tests/fail_test.rs, tests/spec.sh
=> fix: unexpected dup detect for non-cmd/alias function

Cargo.lock, Cargo.toml, src/bin/argc/main.rs, src/command/mod.rs, src/matcher.rs, src/utils.rs, tests/fail_test.rs, tests/macros.rs, tests/snapshots/integration__wrap_test__wrap.snap, tests/tests.rs, tests/wrap_test.rs
```
foo() {
:;
}
eval "$(TERM_WIDTH=`tput cols` argc --argc-eval "$0" "$@")"
```
```
USAGE: test [OPTIONS] [TARGET] <COMMAND>
ARGS:
[TARGET]  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. Sed viverra tellus in hac habitasse platea.
OPTIONS:
--foo <FOO>  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua. Neque laoreet suspendisse libero id.
-h, --help       Print help
COMMANDS:
foo  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
aliqua. Arcu cursus euismod quis viverra.
```
=> feat: support wrap long/multi-line text

src/bin/argc/utils.rs, src/matcher.rs, src/param.rs, tests/compgen.rs, tests/snapshots/integration__compgen__option_multi_vals.snap, tests/snapshots/integration__spec__option_multi_vals.snap, tests/spec.rs
```sh
```
```
USAGE: prog [OPTIONS]
OPTIONS:
--oa <DIR> <FILE>...
-h, --help
```
`-oa dir1 file1 <tab>` compgen files
=> feat: optimize option with mutil vals

src/command/mod.rs, src/matcher.rs, tests/compgen.rs, tests/param_fn.rs, tests/snapshots/integration__compgen__choice_check_vars.snap, tests/snapshots/integration__param_fn__case1.snap, tests/snapshots/integration__param_fn__case2.snap, tests/snapshots/integration__param_fn__case3.snap
argc --argc-eval cargo.sh _choice_fn 'build ' => argc --argc-eval cargo.sh _choice_fn 'cargo build '
=> refactor: eval param-fn no sip first word

src/bin/argc/main.rs, src/compgen.rs, src/utils.rs
=> feat: export current workdir with ARGC_PWD

src/bin/argc/completions/argc.elv, src/bin/argc/completions/argc.ps1, src/bin/argc/completions/argc.xsh, src/bin/argc/completions/argc.zsh, src/compgen.rs, tests/compgen.rs, tests/snapshots/integration__compgen__no_space.snap, tests/snapshots/integration__compgen__subcmds.snap, tests/snapshots/integration__compgen__value_display.snap
```
> argc fn-choice '--bar=abc:def:tsr'
abc:def:tsr  abc:def:xyz  abc:ijk:abc  abc:ijk:xyz
```
=> feat: compgen value dispaly

src/bin/argc/completions/argc.bash, src/compgen.rs, tests/compgen.rs, tests/snapshots/integration__compgen__choice.snap, tests/snapshots/integration__compgen__starts_quote.snap, tests/snapshots/integration__compgen__starts_quote2.snap
```
prog --foo='<tab>
prog '--foo=<tab
prog 'A/B
```
=> feat: compgen supports quotes

src/compgen.rs, tests/snapshots/integration__compgen__choice.snap, tests/snapshots/integration__compgen__mult_char.snap, tests/snapshots/integration__compgen__mult_char2.snap
```diff
prog abc,<tab>
-- abc    def    ijk
++ def    ijk
```
=> feat: compgen dedup multi

src/compgen.rs, tests/compgen.rs, tests/snapshots/integration__compgen__redirect_symbols.snap
```
prog < <tab>
prog > <tab>
```
=> fix: compgen with arg that is redirect symbol

src/compgen.rs, tests/compgen.rs, tests/snapshots/integration__compgen__assing_option_value.snap
Used to distinguish whether choice_fn is used for validate or compgen
=> feat: run choice fn with env ARG_COMPGEN=1

src/compgen.rs, tests/compgen.rs, tests/snapshots/integration__compgen__color.snap
value have three kinds: value, valueOther, valueAnothr; their related colors: green, yellow, read.
=> feat: comp_kind add valueOther

src/compgen.rs, src/matcher.rs, tests/compgen.rs, tests/snapshots/integration__compgen__arg_terminated.snap, tests/snapshots/integration__compgen__assing_option_value.snap, tests/snapshots/integration__compgen__fallback_comp_file.snap, tests/snapshots/integration__compgen__last_arg_option_assign.snap, tests/snapshots/integration__compgen__multiline_doc.snap, tests/snapshots/integration__compgen__multiple.snap, tests/snapshots/integration__compgen__nested_subcmds.snap, tests/snapshots/integration__compgen__no_comp_subcmds.snap, tests/snapshots/integration__compgen__no_flags_options.snap, tests/snapshots/integration__compgen__no_param.snap, tests/snapshots/integration__compgen__option_multi_vals.snap, tests/snapshots/integration__compgen__option_terminated.snap, tests/snapshots/integration__compgen__positionals.snap, tests/snapshots/integration__compgen__redirect_symbols.snap, tests/snapshots/integration__compgen__shorts.snap, tests/snapshots/integration__compgen__special_arg_name.snap, tests/snapshots/integration__compgen__subcmds.snap
```diff
-- echo __argc_value:file
++ echo __argc_value=file
```
=> refactor: use `=` as __argc_var's value sepeartor

src/compgen.rs, src/matcher.rs, tests/compgen.rs, tests/snapshots/integration__compgen__redirect_symbols.snap
=> fix: redirect symbols should complete file

src/command/mod.rs, src/compgen.rs, src/matcher.rs, tests/compgen.rs, tests/snapshots/integration__compgen__delegated.snap
delegate other tools to do compgen
```sh
_choice_delegate() {
fish -c 'complete --do-complete "ls '$@'"'
}
```
=> feat: compgen delegate

src/matcher.rs, tests/snapshots/integration__param_fn__case1.snap, tests/snapshots/integration__param_fn__case2.snap
```bash
cmda() {
:;
}
cmdb() {
:;
}
_choice_fn() {
if [[ "$argc__cmd_fn" == "cmda" ]]; then   # <- use argc__cmd_fn
printf "%s\n" abc def
else
printf "%s\n" x1 y2 z3
fi
}
```
```
$ prog cmda <tab>
abc    def
$ prog cmdb <tab>
x1    x2    x3
```
=> feat: compgen export argc__cmd_fn

src/compgen.rs, src/matcher.rs, src/parser.rs, tests/compgen.rs, tests/main_fn.rs, tests/param_fn.rs, tests/snapshots/integration__compgen__assing_option_value.snap, tests/snapshots/integration__compgen__dashes_at.snap, tests/spec.rs, tests/validate.rs
=> fix: dashes parsing

src/parser.rs, tests/compgen.rs, tests/spec.rs
```diff
-- # @option -D-[`_choice_fn`]
++ # @option -D-*[`_choice_fn`]
```
```
java -DVAR1 -DVAR2
```
=> refactor: prefixed option endsWith `-*`

src/compgen.rs, src/utils.rs
```
prog file:///home/alice/<tab>
```
=> feat: compgen file proto

src/matcher.rs, tests/compgen.rs, tests/scripts/options.sh, tests/snapshots/integration__compgen__flag_cmds.snap, tests/spec.rs
```
```
```
tar -x<tab>
-xj    -xf
```
=> feat: support @meta combine-shorts

src/matcher.rs, src/param.rs, tests/compgen.rs, tests/snapshots/integration__compgen__multiple.snap, tests/snapshots/integration__spec__option_help.snap, tests/spec.rs
```sh
```
`--foo` is multi occurences
`--bar` is multi arguments
=> feat: option multi arguments/occurences

README.md, src/parser.rs
=> refactor: change @meta syntax

Argcfile.sh, src/bin/argc/completions/argc.bash, src/bin/argc/completions/argc.elv, src/bin/argc/completions/argc.fish, src/bin/argc/completions/argc.nu, src/bin/argc/completions/argc.ps1, src/bin/argc/completions/argc.xsh, src/bin/argc/completions/argc.zsh, src/bin/argc/completions/mod.rs, src/bin/argc/main.rs
This pr almost reverts #263
I've noticed that sometimes the `$ARGGC_COMPLETION_BASH` is set, but the argc has not successfully registered the completion function.
=> fix: shell completion scripts

Argcfile.sh, README.md, src/bin/argc/completions/mod.rs, src/compgen.rs, tests/snapshots/integration__compgen__color.snap, tests/snapshots/integration__compgen__desc.snap, tests/snapshots/integration__compgen__desc2.snap, tests/snapshots/integration__compgen__escape.snap, tests/snapshots/integration__compgen__filter_quote.snap, tests/snapshots/integration__compgen__kinds_of.snap, tests/snapshots/integration__compgen__multi_char.snap, tests/snapshots/integration__compgen__multi_char2.snap, tests/snapshots/integration__compgen__multi_parts.snap, tests/snapshots/integration__compgen__multi_parts2.snap, tests/snapshots/integration__compgen__no_space.snap, tests/snapshots/integration__compgen__starts_quote.snap, tests/snapshots/integration__compgen__starts_quote2.snap, tests/snapshots/integration__compgen__suffix.snap, tests/snapshots/integration__compgen__value.snap, tests/snapshots/integration__compgen__value_display.snap
Problems to be solved:
- compgen candidates with spaces don't work
- unable to complete path starts with `~`
tcsh-org/tcsh#83
=> feat: support tcsh

docs/meta.md, docs/task-runner.md, src/argc_value.rs, src/command/mod.rs, src/matcher.rs, tests/meta.rs, tests/snapshots/integration__meta__dotenv.snap, tests/snapshots/integration__meta__dotenv_custom_path.snap, tests/tests.rs
=> feat: support `@meta dotenv`

README.md, docs/meta.md, docs/specification.md, examples/envs.sh, src/argc_value.rs, src/command/mod.rs, src/command/names_checker.rs, src/matcher.rs, src/param.rs, src/parser.rs, tests/env.rs, tests/snapshots/integration__env__env_choice.snap, tests/snapshots/integration__env__env_choice_fn.snap, tests/snapshots/integration__env__env_help.snap, tests/snapshots/integration__env__env_help_subcmd.snap, tests/snapshots/integration__env__env_missing.snap, tests/snapshots/integration__env__env_run.snap, tests/snapshots/integration__export__case1.snap, tests/tests.rs
Define a environment
```sh
```
=> feat: support `@env`

README.md, docs/hooks.md, examples/hooks.sh, src/argc_value.rs, src/command/mod.rs, src/matcher.rs, tests/hook_fn.rs, tests/snapshots/integration__hook_fn__hook_only_after.snap, tests/snapshots/integration__hook_fn__hook_only_before.snap, tests/snapshots/integration__hook_fn__hook_with_main.snap, tests/snapshots/integration__hook_fn__hook_with_subcmd.snap, tests/snapshots/integration__hook_fn__hook_without_subcmd.snap
=> revert: redesign hooks to use only one _argc_init hook (#283)

README.md, src/bin/argc/completions/completion.sh, src/bin/argc/main.rs, src/matcher.rs, tests/cli.rs
Print current shell path
```
$ argc --argc-shell-path 
/usr/bin/bash
```
=> feat: support `--argc-shell-path`

Cargo.lock, Cargo.toml, README.md, src/bin/argc/completions/completion.sh, src/bin/argc/main.rs, src/build.rs, src/command/mod.rs, src/lib.rs, src/mangen.rs, src/manpage.rs, src/matcher.rs, src/param.rs, src/utils.rs, tests/cli.rs, tests/snapshots/integration__compgen__filedir__cd.snap, tests/snapshots/integration__compgen__filedir__cd_win.snap, tests/snapshots/integration__compgen__filedir__value_name.snap, tests/snapshots/integration__compgen__filedir__value_name_win.snap, tests/snapshots/integration__details__nowrap.snap, tests/snapshots/integration__details__wrap.snap, tests/snapshots/integration__details__wrap2.snap
```
argc --argc-mangen <SCRIPT> <OUTDIR>           Generate man pages
```
=> feat: add `--argc-mangen` to generate man pages

docs/specification.md, examples/require-tools.sh, src/argc_value.rs, src/build.rs, src/command/mod.rs, src/matcher.rs, src/utils.rs, tests/snapshots/integration__cli__export.snap, tests/snapshots/integration__validate__require_tools.snap, tests/validate.rs
| syntax                           | scope  | description                                                          |
| :------------------------------- | ------ | :------------------------------------------------------------------- |
| `@meta require-tools <tool>,...` | any    | Require certain tools to be available on the system.                 |
```sh
```
If tools not found, argc will throw error
```
error: missing tools: tool1 tool2
```
=> feat: support @meta require-tools

src/bin/argc/completion.sh, src/bin/argc/main.rs, tests/cli.rs
```
argc --argc-run demo.sh
```
=> feat: add `--argc-run` to run the script

src/build.rs, src/matcher.rs, tests/snapshots/integration__spec__option_single_dash.snap, tests/spec.rs
=> fix: options can accept single dash value

src/argc_value.rs, src/build.rs, src/runtime/mod.rs, src/utils.rs, tests/snapshots/integration__meta__dotenv.snap, tests/snapshots/integration__meta__dotenv_custom_path.snap
- dotenv should not overwrite existing environment variables
- dotenv should support quoted values
=> feat: enhence dotenv

src/bin/argc/main.rs
```
#!/usr/bin/env bash
debug() {
:;
}
```
```
$ argc debug
Error: @unknown(line 4) is unknown tag
$ echo $?
1
```
=> feat: exit 1 for running an invalid argc script

src/bin/argc/main.rs
=> fix: unexpected quotes in ARGC_PWD

Cargo.lock, Cargo.toml, README.md
https://github.com/sigoden/argc/releases/tag/v1.23.0-rc1
=> chore: release v1.23.0

src/completions/argc.zsh
Fixes sigoden/argc-completions#70
=> fix: zsh completion colors

Cargo.lock, Cargo.toml, docs/variables.md, src/compgen.rs, src/shell.rs, tests/snapshots/integration__compgen__desc.snap
**`ARGC_COMPGEN_DESCRIPTION_MAX_WIDTH`**: Maximum width for completion descriptions; excess will be truncated with an ellipsis.
Close #384
=> feat: support ARGC_COMPGEN_DESCRIPTION_MAX_WIDTH
